FROM postgres:15.8

COPY postgresinit/migrations/postgresql15_optimizations.conf /etc/postgresql/postgresql.conf

RUN echo "include = '/etc/postgresql/postgresql.conf'" >> /usr/share/postgresql/postgresql.conf.sample

EXPOSE 5432
