{{- if .Values.jenkinsconnector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jenkinsconnector
  labels:
    {{- include "openidp.labels" . | nindent 4 }}
    app.kubernetes.io/component: jenkinsconnector
spec:
  type: ClusterIP
  ports:
    - port: 8282
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openidp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jenkinsconnector
{{- end }}
