{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    {{- include "openidp.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: ClusterIP
  ports:
    - port: 8281
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openidp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
{{- end }}
