{{- if .Values.scheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    {{- include "openidp.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openidp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
{{- end }}
