apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openidp.fullname" . }}-secret
  labels:
    {{- include "openidp.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.config.adminPassword | b64enc }}
  CONFIG_PASSWORD: {{ .Values.config.configPassword | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  KEYCLOAK_PASSWORD: {{ .Values.keycloak.auth.adminPassword | b64enc }}
  JENKINS_PASSWORD: {{ "650f0ef465ef16b5a8e1bdcbd461973c" | b64enc }}
